import random

def Code_Breaker():
  code = ''.join(random.sample("0123456789", 4))
  code = str(code)
  code_num_list = []
  for num in code:
    code_num_list.append(num)
  
  print("A random 4-digit code has been generated by the computer. (No repeating digits)")
  print("\n--- Hints Key ---\n'Correct' - Number in code, right position\n'Switch' - Number in code, wrong position\n'Incorrect' - Number not in code\n")

  num_of_tries = 0

  while True:
    num_of_tries += 1
    guess_num_list = []
    hints_list = []
    guess = input("\nGuesss the code: ")
    for num in guess:
      guess_num_list.append(num)

    for num in guess_num_list:
      if num in code_num_list:
        if guess_num_list.index(num) == code_num_list.index(num):
          hints_list.append("Correct")
        else:
          hints_list.append("Switch")
      else:
        hints_list.append("Incorrect")
    
    if hints_list == ["Correct", "Correct", "Correct", "Correct"]:
      print("\nThe code was", code)
      print("You won in", num_of_tries, "tries")
      break
    else:
      print("Hints: ", hints_list)
